{{- if .Values.ingress.enabled -}}
{{- $fullName := include "storefront-chart.fullname" . -}}
{{- $svcPort := .Values.service.ports.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "storefront-chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "storefront"
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ $svcPort }}
  {{- end }} 